# S? d?ng image chính th?c c?a OpenJDK làm base image
FROM openjdk:17-jdk-slim

# ??t th? m?c làm vi?c trong container
WORKDIR /app

# Sao chép file JAR ?ã build vào trong container
COPY target/demo_spring.jar /app/demo_spring.jar

# C?u hình volume ?? l?u tr? d? li?u c?a H2 database
VOLUME ["/app/data"]

# Ch?y ?ng d?ng Spring Boot khi container b?t ??u
CMD ["java", "-jar", "demo_spring.jar"]
